#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

GIT_DIR=$(git rev-parse --show-toplevel)
sed  -i "s|[[:digit:]]\+-[[:digit:]]\+-[[:digit:]]\+|$(date -I)|g" "${GIT_DIR}/_config.yml"
git add "${GIT_DIR}/_config.yml"
